export const SET_GAMES = "SET_GAMES";
export const ADD_FAVORITE_GAMES = "ADD_FAVORITE_GAMES";
export const REMOVE_FAVORITE_GAMES = "REMOVE_FAVORITE_GAMES";
export const GET_FAVORITE_GAMES = "GET_FAVORITE_GAMES";
export const SET_FILTERED_GAMES = "SET_FILTERED_GAMES";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_UNIQUE_CATEGORIES = "SET_UNIQUE_CATEGORIES";
export const ADD_PURCHASED_GAMES = "ADD_PURCHASED_GAMES";
export const GET_PURCHASED_GAMES = "GET_PURCHASED_GAMES";


